name: Analysis Testing

on:
  push:
  #    branches:
  #      - "main"
  #      - "release-*"

  pull_request:
    paths-ignore:
      - "docs/**"
    branches:
      - "main"
      - "release-*"

  workflow_dispatch:

  workflow_call:

jobs:
  test:
    name: Build and test from commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install workspace dependencies
        run: |
          npm ci

      - name: Build the project and generate the .vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build
          npm run collect-assets -- --use-workflow-artifacts --branch=main
          npm run dist
          npm run package

      - name: Set vsix suffix
        if: ${{ ! (github.event_name == 'pull_request' && ! github.event.pull_request.merged) }}
        id: set_time
        run: echo "vsix_suffix=$(date +%Y%m%d-%H%M)-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Move vsix
        if: ${{ ! (github.event_name == 'pull_request' && ! github.event.pull_request.merged) }}
        run: |
          cd ./dist
          mv *.vsix konveyor-ai-${{ steps.set_time.outputs.vsix_suffix }}.vsix
          cd ..

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        id: upload-vsix
        #if: ${{ github.event_name == 'pull_request' && !github.event.pull_request.merged }}
        with:
          name: vscode-extension
          path: "dist/*.vsix"
